### ISSUE TITLE
Erro no "LogicTests" :: Método "Installments" :: Linha : 72

### ISSUE THREAD

**Issue by lucashenriquedesouza** [krooze-br/kroozegdschallenge#1]
O resultado esperado está incorreto, devido ao valor mínimo de cada instalação ser 200:

        [TestCase(400, ExpectedResult = 2)]
        [TestCase(40000, ExpectedResult = 12)]
        **[TestCase(100, ExpectedResult = 1)]**
        [TestCase(1000, ExpectedResult = 5)]
        [TestCase(1001, ExpectedResult = 5)]
        public int? Installments(decimal fullPrice)
        {
            return _test.GetInstallments(fullPrice);
        }

**Comment by danielluiz** [comment]
Caro Lucas, 

Installment significa parcela de um pagamento, então o teste está correto, já que é impossível pagar em 0 parcelas, algum pagamento deve ser feito.

Grato,
Daniel Luiz
