### ISSUE TITLE
Injection no Run test

### ISSUE THREAD

**Issue by bvarandas** [krooze-br/kroozegdschallenge#2]
Não sei como registrar os 3 serviços no run tests. Estou abrindo como Issue, mas na verdade esse é a minha única dúvida. Não sei se entendi direito o exercício. Fiz os outros, mas ainda queria completar o de Injection. Segue meu repositório se quiserem dar uma olhada no que eu já fiz. Vou continuar tentando.
https://github.com/bvarandas/Krooze.git

![image](https://user-images.githubusercontent.com/13907905/64836744-ad098f00-d5c1-11e9-97f9-2a3eb315e736.png)

**Comment by danielluiz** [comment]
Tudo bem, essa parte é um pouco mais difícil mesmo, sugiro estudar sobre injeção de dependência que você provavelmente vai conseguir fazer
